name: Cypress Basic Tests

on:
    schedule:
      - cron: '58 17 * * *'
    workflow_dispatch:
jobs:
  cypress-basic-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4

    - name: Install dependencies
      run: npm install

    - name: Run Cypress basic tests
      run: npm run cy:basic-tests

    - name: Upload report artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: mochawesome-report
        path: cypress/reports/html/index.html
        retention-days: 30
        if-no-files-found: warn

      env:
        CI: true