name: Cypress Main Tests

on:
  workflow_dispatch:

jobs:
  cypress-main:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4

    - name: Install dependencies
      run: npm install

    - name: Run Cypress main tests
      run: npm run cy:main
    
    - name: Send notification to Slack
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.PIPELINESLACKCONECTION }}
      run: |
        payload="payload={\"text\":\":rocket: Pipeline '${{ github.workflow }}' launched on branch '${{ github.ref }}' in repository '${{ github.repository }}'\"}"
        curl -X POST --data-urlencode "$payload" $SLACK_WEBHOOK_URL
        
    env:
        CI: true